#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config.sh

docker exec -it ${DOCKER_CONTAINER_NAME} /bin/bash -c "source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && roslaunch turtlebot3_gazebo turtlebot3_world.launch"
# docker exec -it ${DOCKER_CONTAINER_NAME} /bin/bash -c "source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && roslaunch turtlebot3_fake turtlebot3_fake.launch"
